

GET http://192.168.43.102/api/services

###

POST http://192.168.43.102/api/phoneNumberAuth
Content-Type: application/json

{
    "number": "8423160565",
    "user": "user"
}

###

POST http://192.168.43.102/api/otpAuth
Content-Type: application/json

{
    "number": "8423160565",
    "otp": "5812"
}

###

POST http://192.168.43.102/auth/api/getNearestTractor
Content-Type: application/json

{
    "latitude": "26.881735",
    "longitude": "80.993808",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJudW1iZXIiOiI2Mzk0MjMzNjQzIiwiaWF0IjoxNjE3MDMyNjAxLCJleHAiOjE2MTk2MjQ2MDF9.gmG9R0rr9jL2dU2W7UNYBqCtOci4iqWImV2THbJnyO8"
}

###

POST http://192.168.43.102/auth/api/locationLabel
Content-Type: application/json

{
    "latitude": "26.881735",
    "longitude": "80.993808",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJudW1iZXIiOiI2Mzk0MjMzNjQzIiwiaWF0IjoxNjE3MDMyNjAxLCJleHAiOjE2MTk2MjQ2MDF9.gmG9R0rr9jL2dU2W7UNYBqCtOci4iqWImV2THbJnyO8"
}

###

POST http://192.168.43.102/auth/api/changeName
Content-Type: application/json

{
    "name": "case3",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJudW1iZXIiOiI2Mzk0MjMzNjQzIiwibmFtZSI6IlBha29kYSIsInJhdGluZyI6IjQuNjciLCJpYXQiOjE2MTcyMzczNzAsImV4cCI6MTYxOTgyOTM3MH0.Qa0f1Y80GqTWOWrom_hgcnm1g-9VTWKWbhDY5MMrC4o"
}

###

POST http://192.168.43.102/auth/api/getPlaces
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJudW1iZXIiOiI2Mzk0MjMzNjQzIiwiaWF0IjoxNjE3MDMyNjAxLCJleHAiOjE2MTk2MjQ2MDF9.gmG9R0rr9jL2dU2W7UNYBqCtOci4iqWImV2THbJnyO8"
}

###

POST http://192.168.43.102/auth/api/deletePlace
Content-Type: application/json

{
    "id": "3",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJudW1iZXIiOiI2Mzk0MjMzNjQzIiwiaWF0IjoxNjE3MDMyNjAxLCJleHAiOjE2MTk2MjQ2MDF9.gmG9R0rr9jL2dU2W7UNYBqCtOci4iqWImV2THbJnyO8"
}

###

POST http://192.168.43.102/auth/api/getServices
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJudW1iZXIiOiI2Mzk0MjMzNjQzIiwiaWF0IjoxNjE3MDMyNjAxLCJleHAiOjE2MTk2MjQ2MDF9.gmG9R0rr9jL2dU2W7UNYBqCtOci4iqWImV2THbJnyO8"
}

###

POST http://192.168.43.102/auth/api/bookTractor
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJudW1iZXIiOiI4NDIzMTYwNTY1IiwibmFtZSI6IlNoaW5jaGFuIiwicmF0aW5nIjoiNS4wIiwidXJpIjoidW5kZWZpbmVkIiwiaWF0IjoxNjE5MTEwNjE4LCJleHAiOjE2MjE3MDI2MTh9.1HzvTjO5eDdWkszEyDm9tPxsHdNQn_VfFguKWjzFbbU",
    "latitude": "26.8816524",
    "longitude": "80.9935531",
    "area": "1",
    "price": "120"
}

